/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#dce2f7",
        "surface-dim": "#d3daef",
        "on-primary-container": "#541200",
        primary: "#b02f00",
        "surface-container": "#e9edff",
        "surface-container-low": "#f1f3ff",
        "surface-container-highest": "#dce2f7",
        "surface-container-high": "#e1e8fd",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9ff",
        "inverse-on-surface": "#edf0ff",
        outline: "#907067",
        "on-surface": "#141b2b",
        "surface-tint": "#b02f00",
        "on-error-container": "#93000a",
        surface: "#f9f9ff",
        "on-secondary": "#ffffff",
        background: "#f9f9ff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "outline-variant": "#e4beb4",
        "inverse-surface": "#293040",
        "on-background": "#141b2b",
        "on-primary": "#ffffff",
        secondary: "#7e5700",
        "primary-container": "#ff5722",
        "on-secondary-container": "#6a4800",
        "on-surface-variant": "#5b4039",
        "secondary-container": "#feb300",
        "tertiary-container": "#00a572",
        tertiary: "#006c49",
        "on-tertiary-container": "#00311f",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
        margin: "2rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
